version: "3.9"

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - ./server:/app
    command: npm start

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: npm start

  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./server/db:/data